[versions]
minecraft = "1.21.10"
fabric-loader = "0.17.2"

fabric-api = "0.135.0+1.21.10"

# Kotlin
kotlin = "2.2.0"
# Also modrinth version in gradle.properties
fabric-kotlin = "1.13.4+kotlin.2.2.0"

fabric-permissions = "0.5.0"
translations = "2.5.2+1.21.9-pre3"

exposed = "1.0.0-rc-2"
sqlite-jdbc = "3.50.3.0"

konf = "1.1.2"

detekt = "1.23.8"

[libraries]
minecraft = { module = "net.minecraft:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

fabric-permissions = { module = "me.lucko:fabric-permissions-api", version.ref = "fabric-permissions" }
translations = { module = "xyz.nucleoid:server-translations-api", version.ref = "translations" }

exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-migration = { module = "org.jetbrains.exposed:exposed-migration", version.ref = "exposed" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }

konf-core = { module = "com.uchuhimo:konf-core", version.ref = "konf"}
konf-toml = { module = "com.uchuhimo:konf-toml", version.ref = "konf"}
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
loom = { id = "fabric-loom", version = "1.11.+" }
git_hooks = { id = "com.github.jakemarsden.git-hooks", version = "0.0.2" }
